/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pengarsipan_skripsi;

import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Point;

/*
 *
 * @author  3411201085 Adhani Mulianti
            3411201089 Rayi Syifa Adriana Firmansyah
            3411201090 Adisti Dwi Susanti
            3411201094 Alfin Gerliandeva
 */
public class Form_kategoriSkripsi extends javax.swing.JFrame {
    
    pengarsipan_skripsi.Koneksi konek = new pengarsipan_skripsi.Koneksi();
    /**
     * Creates new form Form_kategoriSkripsi
     */
    public Form_kategoriSkripsi() {
        initComponents();
        initUI();
    }
    
    private void initUI(){
        Dimension windowSize = getSize();
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Point centerPoint = ge.getCenterPoint();
        
        int dx = centerPoint.x - windowSize.width / 2;
        int dy = centerPoint.y - windowSize.height / 2;    
        setLocation(dx, dy);   
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_id = new javax.swing.JTextField();
        jP_menu = new javax.swing.JPanel();
        lbl_data_kategori_skripsi = new javax.swing.JLabel();
        lbl_tambahdata = new javax.swing.JLabel();
        lbl_kode_skripsi = new javax.swing.JLabel();
        lbl_kategori_skripsi = new javax.swing.JLabel();
        lbl_kategori_studi = new javax.swing.JLabel();
        tf_kode_skripsi = new javax.swing.JTextField();
        tf_kategori_skripsi = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        btn_tambah = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();
        t_kategori_skripsi = new javax.swing.JScrollPane();
        t_data_kategori_skripsi = new javax.swing.JTable();
        lbl_jumdata = new javax.swing.JLabel();
        btn_validasiK_Skripsi = new javax.swing.JButton();
        lbl_validasiK_Skripsi = new javax.swing.JLabel();
        lbl_validasiKA_Skripsi = new javax.swing.JLabel();
        btn_validasiKA_Skripsi = new javax.swing.JButton();
        cb_kategori_studi = new javax.swing.JComboBox<>();

        tf_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idActionPerformed(evt);
            }
        });

        setResizable(false);

        jP_menu.setBackground(new java.awt.Color(74, 101, 114));

        lbl_data_kategori_skripsi.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lbl_data_kategori_skripsi.setForeground(new java.awt.Color(255, 255, 255));
        lbl_data_kategori_skripsi.setText("DATA KATEGORI SKRIPSI");

        javax.swing.GroupLayout jP_menuLayout = new javax.swing.GroupLayout(jP_menu);
        jP_menu.setLayout(jP_menuLayout);
        jP_menuLayout.setHorizontalGroup(
            jP_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_menuLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(lbl_data_kategori_skripsi)
                .addGap(180, 180, 180))
        );
        jP_menuLayout.setVerticalGroup(
            jP_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_menuLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lbl_data_kategori_skripsi)
                .addGap(40, 40, 40))
        );

        lbl_tambahdata.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_tambahdata.setText("Tambah Data");

        lbl_kode_skripsi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_kode_skripsi.setText("KODE SKRIPSI          :");

        lbl_kategori_skripsi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_kategori_skripsi.setText("KATEGORI SKRIPSI  :");

        lbl_kategori_studi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_kategori_studi.setText("KATEGORI STUDI      :");

        tf_kode_skripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_kode_skripsiActionPerformed(evt);
            }
        });

        tf_kategori_skripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_kategori_skripsiActionPerformed(evt);
            }
        });

        btn_simpan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pengarsipan_skripsi.assets/save-solid.png"))); // NOI18N
        btn_simpan.setText("SIMPAN");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_batal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pengarsipan_skripsi.assets/backward-solid.png"))); // NOI18N
        btn_batal.setText("BATAL");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        btn_tambah.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pengarsipan_skripsi.assets/plus-solid.png"))); // NOI18N
        btn_tambah.setText("TAMBAH");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_edit.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pengarsipan_skripsi.assets/pen-solid.png"))); // NOI18N
        btn_edit.setText("EDIT");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_hapus.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pengarsipan_skripsi.assets/trash-solid.png"))); // NOI18N
        btn_hapus.setText("HAPUS");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_refresh.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pengarsipan_skripsi.assets/recycle-solid.png"))); // NOI18N
        btn_refresh.setText("REFRESH");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        t_data_kategori_skripsi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "KODE SKRIPSI", "KATEGORI SKRIPSI", "KATEGORI STUDI"
            }
        ));
        t_data_kategori_skripsi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_data_kategori_skripsiMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                t_data_kategori_skripsiMouseReleased(evt);
            }
        });
        t_data_kategori_skripsi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t_data_kategori_skripsiKeyReleased(evt);
            }
        });
        t_kategori_skripsi.setViewportView(t_data_kategori_skripsi);

        lbl_jumdata.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_jumdata.setText("Jumlah Data : ");

        btn_validasiK_Skripsi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pengarsipan_skripsi.assets/check-solid.png"))); // NOI18N
        btn_validasiK_Skripsi.setContentAreaFilled(false);
        btn_validasiK_Skripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_validasiK_SkripsiActionPerformed(evt);
            }
        });

        btn_validasiKA_Skripsi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pengarsipan_skripsi.assets/check-solid.png"))); // NOI18N
        btn_validasiKA_Skripsi.setContentAreaFilled(false);
        btn_validasiKA_Skripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_validasiKA_SkripsiActionPerformed(evt);
            }
        });

        cb_kategori_studi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--PILIH KATEGORI--", "DSE", "AIG", "Kimia Analitika", "Kimia Fisika", "Biokimia", "Kimia Organik", "Kimia Anorganik", "Sistem Informasi" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_tambahdata)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(138, 138, 138)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btn_simpan)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btn_batal))
                                        .addComponent(lbl_validasiK_Skripsi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tf_kode_skripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbl_kategori_studi)
                                    .addGap(18, 18, 18)
                                    .addComponent(cb_kategori_studi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_kode_skripsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_kategori_skripsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(tf_kategori_skripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_validasiKA_Skripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_validasiK_Skripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btn_validasiKA_Skripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(t_kategori_skripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_tambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(btn_refresh)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_jumdata)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jP_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lbl_tambahdata)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_tambah)
                            .addComponent(btn_edit)
                            .addComponent(btn_hapus)
                            .addComponent(btn_refresh))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_validasiK_Skripsi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_kode_skripsi)
                                .addComponent(tf_kode_skripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)
                        .addComponent(lbl_validasiK_Skripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_kategori_skripsi)
                                .addComponent(tf_kategori_skripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_validasiKA_Skripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lbl_validasiKA_Skripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_kategori_studi)
                            .addComponent(cb_kategori_studi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_simpan)
                            .addComponent(btn_batal)))
                    .addComponent(t_kategori_skripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_jumdata)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_kategori_skripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_kategori_skripsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_kategori_skripsiActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void t_data_kategori_skripsiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_data_kategori_skripsiMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_t_data_kategori_skripsiMouseClicked

    private void t_data_kategori_skripsiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_data_kategori_skripsiMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_t_data_kategori_skripsiMouseReleased

    private void t_data_kategori_skripsiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_data_kategori_skripsiKeyReleased
        // TODO add your handling code here:
      
    }//GEN-LAST:event_t_data_kategori_skripsiKeyReleased

    private void tf_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_idActionPerformed

    private void tf_kode_skripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_kode_skripsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_kode_skripsiActionPerformed

    private void btn_validasiK_SkripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_validasiK_SkripsiActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btn_validasiK_SkripsiActionPerformed

    private void btn_validasiKA_SkripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_validasiKA_SkripsiActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_validasiKA_SkripsiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_kategoriSkripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_kategoriSkripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_kategoriSkripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_kategoriSkripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_kategoriSkripsi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_validasiKA_Skripsi;
    private javax.swing.JButton btn_validasiK_Skripsi;
    private javax.swing.JComboBox<String> cb_kategori_studi;
    private javax.swing.JPanel jP_menu;
    private javax.swing.JLabel lbl_data_kategori_skripsi;
    private javax.swing.JLabel lbl_jumdata;
    private javax.swing.JLabel lbl_kategori_skripsi;
    private javax.swing.JLabel lbl_kategori_studi;
    private javax.swing.JLabel lbl_kode_skripsi;
    private javax.swing.JLabel lbl_tambahdata;
    private javax.swing.JLabel lbl_validasiKA_Skripsi;
    private javax.swing.JLabel lbl_validasiK_Skripsi;
    private javax.swing.JTable t_data_kategori_skripsi;
    private javax.swing.JScrollPane t_kategori_skripsi;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_kategori_skripsi;
    private javax.swing.JTextField tf_kode_skripsi;
    // End of variables declaration//GEN-END:variables
}
