/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pengarsipan_skripsi;

import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Point;

/*
 *
 * @author  3411201085 Adhani Mulianti
            3411201089 Rayi Syifa Adriana Firmansyah
            3411201090 Adisti Dwi Susanti
            3411201094 Alfin Gerliandeva
 */
public class Pencarian_Skripsi extends javax.swing.JFrame {
    
    pengarsipan_skripsi.Koneksi konek = new pengarsipan_skripsi.Koneksi();

    /*
     * Creates new form Pencarian_Skripsi
     */
    public Pencarian_Skripsi() {
        initComponents();
        initUI();
    }
    
    private void initUI(){
        Dimension windowSize = getSize();
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Point centerPoint = ge.getCenterPoint();
        
        int dx = centerPoint.x - windowSize.width / 2;
        int dy = centerPoint.y - windowSize.height / 2;    
        setLocation(dx, dy);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_id = new javax.swing.JTextField();
        jP_menu = new javax.swing.JPanel();
        lbl_pencarian_skripsi = new javax.swing.JLabel();
        lbl_cari = new javax.swing.JLabel();
        lbl_kata = new javax.swing.JLabel();
        tf_cari = new javax.swing.JTextField();
        btn_refresh = new javax.swing.JButton();
        t_pencarian_skripsi = new javax.swing.JScrollPane();
        t_data_pencarian_skripsi = new javax.swing.JTable();
        lbl_jumdata = new javax.swing.JLabel();
        btn_clear = new javax.swing.JButton();

        tf_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idActionPerformed(evt);
            }
        });

        setResizable(false);

        jP_menu.setBackground(new java.awt.Color(74, 101, 114));

        lbl_pencarian_skripsi.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lbl_pencarian_skripsi.setForeground(new java.awt.Color(255, 255, 255));
        lbl_pencarian_skripsi.setText("MENU PENCARIAN SKRIPSI");

        javax.swing.GroupLayout jP_menuLayout = new javax.swing.GroupLayout(jP_menu);
        jP_menu.setLayout(jP_menuLayout);
        jP_menuLayout.setHorizontalGroup(
            jP_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_menuLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(lbl_pencarian_skripsi)
                .addGap(250, 250, 250))
        );
        jP_menuLayout.setVerticalGroup(
            jP_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_menuLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lbl_pencarian_skripsi)
                .addGap(40, 40, 40))
        );

        lbl_cari.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_cari.setText("Pencarian Skripsi");

        lbl_kata.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_kata.setText("Masukkan Kata           :");

        tf_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cariActionPerformed(evt);
            }
        });
        tf_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_cariKeyReleased(evt);
            }
        });

        btn_refresh.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pengarsipan_skripsi.assets/recycle-solid.png"))); // NOI18N
        btn_refresh.setText("REFRESH");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        t_data_pencarian_skripsi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "JUDUL SKRIPSI", "KATEGORI STUDI", "NAMA MAHASISWA", "NAMA DOSEN"
            }
        ));
        t_data_pencarian_skripsi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_data_pencarian_skripsiMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                t_data_pencarian_skripsiMouseReleased(evt);
            }
        });
        t_data_pencarian_skripsi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t_data_pencarian_skripsiKeyReleased(evt);
            }
        });
        t_pencarian_skripsi.setViewportView(t_data_pencarian_skripsi);

        lbl_jumdata.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_jumdata.setText("Jumlah Data : ");

        btn_clear.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pengarsipan_skripsi.assets/trash-restore-solid.png"))); // NOI18N
        btn_clear.setText("CLEAR");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_kata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_cari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btn_refresh)))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(t_pencarian_skripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_jumdata)
                        .addGap(48, 48, 48))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jP_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_cari)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_kata)
                            .addComponent(tf_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_clear)
                            .addComponent(btn_refresh)))
                    .addComponent(t_pencarian_skripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_jumdata)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_cariActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void t_data_pencarian_skripsiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_data_pencarian_skripsiMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_t_data_pencarian_skripsiMouseClicked

    private void t_data_pencarian_skripsiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_data_pencarian_skripsiMouseReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_t_data_pencarian_skripsiMouseReleased

    private void t_data_pencarian_skripsiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_data_pencarian_skripsiKeyReleased
        // TODO add your handling code here:
      
    }//GEN-LAST:event_t_data_pencarian_skripsiKeyReleased

    private void tf_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_idActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btn_clearActionPerformed

    private void tf_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_cariKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tf_cariKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pencarian_Skripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pencarian_Skripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pencarian_Skripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pencarian_Skripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pencarian_Skripsi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JPanel jP_menu;
    private javax.swing.JLabel lbl_cari;
    private javax.swing.JLabel lbl_jumdata;
    private javax.swing.JLabel lbl_kata;
    private javax.swing.JLabel lbl_pencarian_skripsi;
    private javax.swing.JTable t_data_pencarian_skripsi;
    private javax.swing.JScrollPane t_pencarian_skripsi;
    private javax.swing.JTextField tf_cari;
    private javax.swing.JTextField tf_id;
    // End of variables declaration//GEN-END:variables
}
